### ISSUE TITLE
like facebook button  very problematic and unuseless

### ISSUE THREAD

**Issue by HectorRPL** [cornflourblue/jw-angular-social-buttons#1]
I hope you can remove the like button from facebook, it is not very useful, it does not achieve standardization with other social, it can not be removed, it causes errors in the browser.

**Comment by cornflourblue** [comment]
All the buttons are running fine when i test them, can you be a bit more specific about the issue you're having? Please post a code sample to StackBlitz that shows the issue.

**Comment by cornflourblue** [comment]
If you're still having an issue please post a small reproduction and I'll check it out.

**Comment by lilling** [comment]
I think what @HectorRPL suggested and if not I'm proposing it. to add the option not to show the like button.
